name: Build and Deploy Dev

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [ testing ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: create a new maven-repository
        run: git remote add maven-repo https://github.com/blusalt-fs/maven-repository
      - name: Commit new branch to maven repository
        run: git push maven-repo testing:commons-service
        env: 
          token: ${{ secrets.ACCESSS_TOKEN_PACKAGES }}
